gpu: '1'
gpu_2: '5'
training:
    learning_rate: 0.0002
    batch_size: 4
    epochs: 85
    early_stopping_patience: 8
    early_stopping_delta: 0
    accumulate_gradients: 3
    max_samples : 5000
    num_workers : 4
    
grid_search_training:
    initial_batch_size: 5
    epochs: 100
    learning_rate: 0.0002

dsfno:
    modes: 10
    n_channels: 32
    n_residual_blocks: 3
    n_operator_blocks: 2
    apply_constraint: True

fno_1:
    modes: 20
    n_channels: 64
    n_residual_blocks: 3
    n_operator_blocks: 2
    apply_constraint: True
    shifting_modes: 4

fno_2:
    in_channel: 5
    n_channels: 32
    n_residual_blocks: 2
    n_operator_blocks: 2
    modes: 16
    shifting_modes: 3
    apply_constraint: False
    last_layer_kernel: 3
    last_layer_constraint: 'relu'

grid_fno2:
    modes: [12, 22, 32]
    chan: [24, 32, 64]
    res: [3]
    op: [1, 2, 3]
    last_layer_constraint: ['relu', 'exp']

grid_edsr:
    n_resblocks: [16, 32, 64]
    n_feats: [64, 128]
    kernel_size: [3, 5]
    activation_f: [False]

edsr:
    n_resblocks: 0
    n_feats: 0
    kernel_size: 0
    activation_f: False
cnn:
    n_feats: 64
    n_resblocks: 5

data:
    upsample_factor: 4

grid_dsfno:
    modes: [4, 16, 32]
    n_channels: [8, 16, 32]
    n_residual_blocks: [2, 6, 8]
    n_operator_blocks: [2, 4, 6]

turbulent_sim:
    runtime_debug: False
    first_order_fb: False
    progress_bar: False
    dimensionality: 3
    num_ghost_cells: 2
    box_size: 1.0
    num_cells: 128
    fixed_timestep: False
    return_snapshots: True
    num_snapshots: 100
    turbulence_slope: -2
    kmin: 2
    kmax: 64
    max_sims: 500
    gamma: 5/3
    dt_max: 0.1
    wanted_rms: 50