hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false

runtime:
  cuda_visible_devices: 0

paths:
  experiment_folder: experiments/cfno_2/experiment_2

data:
  kind: 3d
  kwargs: {}
  validation_start_index: 5000

evaluation:
  initial_batch_size: 16
  min_batch_size: 1
  num_workers: 2
  upsample_factor: 4
