name: dsfno
module: src.model.models_dsfno_3d
class_name: DSFNO
params:
  in_channel: 5
  modes: 10
  n_channels: 32
  n_residual_blocks: 3
  n_operator_blocks: 2
  apply_constraint: true
tag_template: "in{in_channel}_m{modes}_nc{n_channels}_res{n_residual_blocks}_op{n_operator_blocks}_ac{apply_constraint}_2"
