name: fno_2_2d
module: src.model.models_fno2_2d
class_name: FNO_2
params:
  in_channel: 4
  modes: 16
  n_channels: 32
  n_residual_blocks: 2
  n_operator_blocks: 2
  apply_constraint: false
  shifting_modes: 3
  last_layer_kernel: 3
tag_template: "m{modes}_nc{n_channels}_res{n_residual_blocks}_op{n_operator_blocks}_ac{apply_constraint_int}_lk{last_layer_kernel}"
