autocvd:
  enabled: true
  num_gpus: 1
timestamp_format: "%Y-%m-%d_%H-%M-%S"
date_format: "%Y-%m-%d"
output:
  enabled: true
  root_dir: experiments
  run_dir_template: "cfno_2_2d/{timestamp}_{model_tag}"
  weights_name_template: "weights.pt"
  loss_curve_name_template: "loss_curve.png"
  config_name: "config.yaml"
  save_config: true
  save_weights: true
  save_loss_curve: true
